"""add language to posts

Revision ID: 397be64c5d75
Revises: ffb71f509aa3
Create Date: 2019-03-25 15:38:00.899608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397be64c5d75'
down_revision = 'ffb71f509aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
